services:
  db:
    image: postgres:16
    container_name: carspixel_db
    environment:
      POSTGRES_USER: carspixel
      POSTGRES_PASSWORD: carspixel
      POSTGRES_DB: carspixel
    ports:
      - "5432:5432"
    volumes:
      - carspixel_pg:/var/lib/postgresql/data

volumes:
  carspixel_pg:
